In [1]:
import numpy as np

def decision_matrix(x, y, wx, wy, size):
    # Assuming x, y, wx, wy are lists or numpy arrays
    # Assuming size is a scalar or tuple indicating the size of the decision matrix

    # Example of combining the inputs in a way to form a decision matrix
    # This is a placeholder; the actual implementation depends on the specifics of decisionMatrix in R
    matrix = np.zeros((size, size))
    for i in range(size):
        for j in range(size):
            matrix[i, j] = x[i] * wx + y[j] * wy
    
    return matrix

# Example usage
x = [1, 2, 3]
y = [4, 5, 6]
wx = 0.1
wy = 0.2
size = 3

matrix = decision_matrix(x, y, wx, wy, size)
print(matrix)


[[0.9 1.1 1.3]
 [1.  1.2 1.4]
 [1.1 1.3 1.5]]
